### PR TITLE
Website: Imperial units, down indicator, default table view

### PR DESCRIPTION
**Pull request by LukePrior**
I have solved an edge case where if the page is loaded on a low-resolution (720p) monitor the table is too large so it will default to the mobile view in this case.

I have added support for displaying Imperial units which solves #383 (when the setting is applied the page is refreshed as this is the only way I could find to update table headers).

I have also implemented a down icon if the settings menu can be scrolled.

Please check that these features all work as expected.

Thanks

### CODE REVIEW

**Comment by darksidelemm** [comment]
I like the down arrow to indicate scrolling!

**Comment by LukePrior** [comment]
> I like the down arrow to indicate scrolling!

Yeah I think it's a decent solution, it is a little bit buggy with going away at some points but it doesn't break anything else and I think it's better than the alternative of no indication.

**Comment by darksidelemm** [comment]
Yep. Looking really good! Haven't tested the imperial changes with real data, but i can see the field titles changing.

I think we're not that far off being able to release these changes now. There's some Sondehub backend stuff that needs to be checked first though (relating to station position uploads).

**Comment by darksidelemm** [comment]
@LukePrior are there any other changes you think need doing before releasing 1.5.1? 
I've successfully tested the new listeners upload endpoint ( https://github.com/projecthorus/sondehub-infra/wiki/API-(Beta)#put-1 ), so that's all ready to go. I'm just making some documentation tweaks and then think we're ready to go!

**Comment by LukePrior** [comment]
> @LukePrior are there any other changes you think need doing before releasing 1.5.1?
> I've successfully tested the new listeners upload endpoint ( https://github.com/projecthorus/sondehub-infra/wiki/API-(Beta)#put-1 ), so that's all ready to go. I'm just making some documentation tweaks and then think we're ready to go!

I think everything is good on my end.

**Comment by LukePrior** [comment]
Hey @darksidelemm completely unrelated to this PR but didn't want to open a new thread.

I saw you are working on a new [tracking](https://github.com/projecthorus/sondehub-tracker) interface utilizing the new SondeHub database. I was just wondering now that we are pushing data to it is there a publicly hosted version available or does it need to be hosted locally while it's still under development?

Cheers

**Comment by darksidelemm** [comment]
It's up at https://v2.sondehub.org/ - but is very much still in beta. Quite a few things not working yet!

**Comment by LukePrior** [comment]
> It's up at https://v2.sondehub.org/ - but is very much still in beta. Quite a few things not working yet!

Cool, it feels faster.

I would recommend updating the sidebar with the new URL.

image

**Comment by darksidelemm** [comment]
Didn't even spot that :-) Fixed.

**Comment by LukePrior** [comment]
> Didn't even spot that :-) Fixed.

Does the new interface feature support for direct URL from the interface yet. 

The old interface accepted `https://sondehub.org/S2450063` but `https://v2.sondehub.org/S2450063` throws an access denied error. Should I format the URL differently or is this feature just not added yet?

Cheers

**Comment by TheSkorm** [comment]
Feature hasn't been updated yet. This will be added closer to v2 release. I'm intending to keep the same URLs for the frontend, but while it's in testing it needs to live somewhere

You can instead just use the query parameter for now: https://v2.sondehub.org/#!mt=roadmap&mz=11&qm=3_hours&q=S2810026

**Comment by LukePrior** [comment]
> Feature hasn't been updated yet. This will be added closer to v2 release. I'm intending to keep the same URLs for the frontend, but while it's in testing it needs to live somewhere
> 
> You can instead just use the query parameter for now: https://v2.sondehub.org/#!mt=roadmap&mz=11&qm=3_hours&q=S2810026

Cheers, that works great. Do you have a V2 replacement for card yet?

`https://sondehub.org/card/S2810026`

**Comment by LukePrior** [comment]
@darksidelemm 

I'm running a version on my personal build with a wind overlay, you can see the changes [here](https://github.com/LukePrior/radiosonde_auto_rx/tree/testing). Is this something you would want in the main release?

**Comment by darksidelemm** [comment]
Sondehub.org/card/ is using v2 right now. There were some slight API changes, but nothing major.

Do you have a screenshot of your changes? I'm not really sure displaying wind data from GFS is something necessary on auto_rx tbh...

What I would *really* like to see at some point is a live skew-T diagram from the sounding data, however this does require valid temperature and humidity (well, dew point for skewT) data. There's a nice library to do the skew-T plots here: https://github.com/dfelix/skewt-js

This would be really useful for both auto_rx, to get 'live' soundings, and also on sondehub.org/card/ to get historical sounding data. The telemetry data will require a bit of massaging to get into the right format for use with that library.

**Comment by LukePrior** [comment]
> Sondehub.org/card/ is using v2 right now. There were some slight API changes, but nothing major.

Is Sondehub v2 down? cards and the new interface don't seem to be working.

> Do you have a screenshot of your changes? I'm not really sure displaying wind data from GFS is something necessary on auto_rx

See below. You can also see an example [here](https://danwild.github.io/leaflet-velocity/).
image

> What I would _really_ like to see at some point is a live skew-T diagram from the sounding data, however this does require valid temperature and humidity (well, dew point for skewT) data.

I can help with general questions but I don't even know what a skew-T diagram is or what it's used for so I won't be too much help with that.

> There's a nice library to do the skew-T plots here: https://github.com/dfelix/skewt-js

The [example](http://meteo.clubeicaro.pt/skewt.html) for the library seems to be offline.

**Comment by darksidelemm** [comment]
Here's an example of a Skew-T plot:

Screen Shot 2021-04-12 at 6 54 29 pm

The Skew-T plot is the usual format for representing radiosonde soundings: https://en.wikipedia.org/wiki/Skew-T_log-P_diagram

As cool as it looks, I don't think the wind data is necessary in the auto_rx GUI. Maybe as an overlay on the sondehub tracker, though that's running on the GMaps API, so I'm not sure it would be possible.  Realistically the display of a single wind layer doesn't provide much information about an upcoming radiosonde flight - the directions will vary drastically with altitude, so you would need all the different layers, which is a bit more than was ever intended for the auto_rx gui - scope creep!

**Comment by mhaberler** [comment]
the skewt-js repo above was forked by @rittels into https://github.com/rittels/skewt-js and worked on quite a bit
it is the basis for the [windy radiosonde plugin](https://github.com/rittels/windy-plugin-radiosonde), you might give that a try like so (desktop):

https://windy.com -> top left menu -> Install Windy plugin -> Load plugin directly from npm -> type 'radiosonde' such the full name is windy-plugin-radiosonde -> Load & activate

then select an ascent on the map
example:

Bildschirmfoto 2021-04-12 um 11 30 11

I also stumbled across this library which does skew-t, Stüve and hodographs:

https://www.npmjs.com/package/meteojs
https://chird.github.io/meteoJS/examples/

it is used in http://www.iv3ryq.it/MySondy/

**Comment by LukePrior** [comment]
> Here's an example of a Skew-T plot:

Huh interesting.

> I don't think the wind data is necessary in the auto_rx GUI

Yeah after using it for a few days I think I would have to agree, I set it 17km altitude but it doesn't give that great a prediction. 

Did you make the website that shows predicted landing sites for the next few days from each launch site in Australia?

So will the new SondeHub use Google Maps I thought there were licensing issues with the API in recent years?

**Comment by darksidelemm** [comment]
The new sondehub tracker will basically be the same as the old sondehub tracker, but using the V2 API. This is mainly because a heap of work has gone into the tracker, and it's a huge job to re-write it all to use Leaflet. GMaps API it is for now... 

If you mean https://rfhead.net/sondes/ then yep, that's me :-)  

@mhaberler  Yep, I figure being able to see that data live in auto_rx, or on the sondehub tracker would be pretty cool.

**Comment by darksidelemm** [comment]
Also yes, the v2 DB is down at the moment (thanks AWS). @TheSkorm is working on it...

**Comment by mhaberler** [comment]
> @mhaberler Yep, I figure being able to see that data live in auto_rx, or on the sondehub tracker would be pretty cool.

that is what http://www.iv3ryq.it/MySondy/ is in fact doing - try this: click a flying sonde, then on the graph icon top right of the simulated  LCD display:

Bildschirmfoto 2021-04-12 um 11 39 45

**Comment by darksidelemm** [comment]
Yep, that kind of thing is what we're going for... just without all the weird LCD display stuff :-)

**Comment by mhaberler** [comment]
> Yep, that kind of thing is what we're going for... just without all the weird LCD display stuff :-)

you're clearly unappereciative of Italian _bella figura_

**Comment by mhaberler** [comment]
this code is also a potential candidate:

http://www.ryansobash.com/d3-skewt/
https://github.com/rsobash/d3-skewt

**Comment by darksidelemm** [comment]
Just personal preference :-) 

Hopefully Mirko adds Sondehub DB support to MySondy... it would be nice to have other contributors. 
Bev (Sondemonitor) is working on adding support at the moment.

**Comment by mhaberler** [comment]
that'd be great - I see pretty good coverage in northern Italy from Mirko, and I jumped the hoop and got me an APRS feed from radiosondy which has many of those stations

but I'd gladly skip the APRS stuff which is a one-off for me

**Comment by darksidelemm** [comment]
Yes, APRS is not a good medium for this kind of data. Very limiting (e.g. 9 character object IDs). 
Even worse when it ends up on the wider APRS-IS network. I'd heard that radiosonde traffic is actually a rather large proportion of overall APRS-IS traffic nowadays!

It's a shame MySondy is closed source, else I'd be interested in contributing SondeHub upload support.

**Comment by darksidelemm** [comment]
For now, open documentation of the API and format, and the hope that others will be interested enough to add support will have to do!

**Comment by IZ4PNN** [comment]
Hi guys!
It is not excluded that I add support to SondeHub, only I have many requests (especially for MySondy Go) and little time.
MySondy Server is not closed source, I have already sent the sources to several guys of good will :)
If darksidelemm wants to work, I would be happy to give him everything he needs :)

73

**Comment by darksidelemm** [comment]
Can you point me to a github repo? What language is it coded in?

**Comment by IZ4PNN** [comment]
Sorry... I don't use github... I can send you a link to download them if you tell me an email address.

The part of the code that pertains to this is in C.

This is a modified version of dxlaprs (OE5DXL) then it keeps the licenses:

https://github.com/oe5hpm/dxlAPRS

The work should be done in the raspberry software which sends data to MySondy Server and MySondy Finder (the Android App).

MySondy Go on the other hand is a completely different project.

73

**Comment by darksidelemm** [comment]
OK, adding support to the dxlAPRS Codebase is best done by someone actually familiar with that codebase, not by me. I've had a look into it before (trying to figure out the M10 serial number calculations) and my head hurt afterwards.....

I'd suggest there would be more value in MySondy Go users, operating handheld / portable, hooked into their phones, being able to contribute positions to the Sondehub DB. I guess this would be done in the MySondy Finder app, since the MySondy Go only talks to the phone via bluetooth serial? Doing HTTPS PUT requests in Java isn't all that difficult...

**Comment by LukePrior** [comment]
> I'd suggest there would be more value in MySondy Go users, operating handheld / portable, hooked into their phones, being able to contribute positions to the Sondehub DB.

This would be very useful indeed.

**Comment by darksidelemm** [comment]
Hmm, I just noted that the rdz_ttgo_sonde decoder ( https://github.com/dl9rdz/rdz_ttgo_sonde/ ) does output via APRS right now, and is based around the ESP32 libraries (which has a HTTPClientSecure library for HTTPS requests). This might be a suitable target platform to implement something on... I don't have any suitable hardware at the moment though.

**Comment by IZ4PNN** [comment]
MySondy Finder it is the Android version of MySondy Server, so the raspberry with modified dxlaprs always sends the data.

MySondy Go is another project, here the question is a little more complicated, as I said I don't rule out adding support to Sondehub but i need time :)

**Comment by LukePrior** [comment]
> Hmm, I just noted that the rdz_ttgo_sonde decoder ( https://github.com/dl9rdz/rdz_ttgo_sonde/ ) does output via APRS right now, and is based around the ESP32 libraries (which has a HTTPClientSecure library for HTTPS requests). This might be a suitable target platform to implement something on... I don't have any suitable hardware at the moment though.

I'm using this at the moment on a TTGO LORA v2.1_1.6 and it works well so the addition of Sondehub support would be great.

**Comment by darksidelemm** [comment]
This looks to be the point where received packets are passed on to other systems: https://github.com/dl9rdz/rdz_ttgo_sonde/blob/devel/RX_FSK/RX_FSK.ino#L2087

There's already an example there of producing a JSON blob - I suspect it wouldn't be *that* much extra work to generate something in a suitable format compatible with SondeHub. I'm unsure how much Flash/RAM the HTTPClientSecure library uses.
You probably wouldn't want to send every position in an individual request though... You'd either need to batch them up like auto_rx does (which requires more RAM) then submit them, or only send updates every X frames (or every Y seconds).

**Comment by LukePrior** [comment]
> If you mean https://rfhead.net/sondes/ then yep, that's me :-)

Is the code for that open source?

**Comment by snh** [comment]
>> If you mean https://rfhead.net/sondes/ then yep, that's me :-)
>
> Is the code for that open source?

I believe https://github.com/darksidelemm/cusf_predictor_wrapper/tree/master/apps contains the code behind this.

**Comment by darksidelemm** [comment]
Yup, that's it! 

This code is essentially what i'm doing: https://github.com/darksidelemm/cusf_predictor_wrapper/blob/master/apps/sonde_predict.sh

In my case I'm grabbing wind data for the Australian region (using the 0p25_1hr model), and then running sonde predictions for a range of sites:
```
# YPAD
python sonde_predict.py -o sonde_predictions -s Adelaide
scp sonde_predictions.json <my server>:~/www/sondes/adelaide/

# Mt Gambier
python sonde_predict.py --latitude=-37.7478 --longitude=140.7752 -s "Mt Gambier" --step=24 --time="23:15Z"
scp sonde_predictions.json <my server>:~/www/sondes/mtgambier/

# Tullamarine
python sonde_predict.py --latitude=-37.6657 --longitude=144.8317 -s Tullamarine
scp sonde_predictions.json <my server>:~/www/sondes/tullamarine/

# Brisbane
python sonde_predict.py --latitude=-27.3914 --longitude=153.1297 -s Brisbane --time="23:15Z" --step 24
scp sonde_predictions.json <my server>t:~/www/sondes/brisbane
```

If i was to do this again I'd probably just do it dynamically in the browser using the Tawhiri API. I've already written code to grab and plot data from the Tawhiri API (on https://predict.sondehub.org ), with the Tawhiri specific code here: https://github.com/darksidelemm/leaflet_predictor/blob/master/js/pred/pred-new.js#L68

**Pull request merged**
