### PR TITLE
Update mts01mod for hor.vel and temp

### PR DESCRIPTION
**Pull request by icalik**
I tested it with MTS01 probe and then I was able to see temperature value
Updated README file to enable temp on Meteosis MTS01

### CODE REVIEW

**Comment by darksidelemm** [comment]
@rs1729 have you seen this?

**Comment by icalik** [comment]
> @rs1729 have you seen this?

yes i hve copied from there, like what you did. is it a problematic thing?

**Comment by darksidelemm** [comment]
Nope, that's fine! I hadn't spotted the changes. Will merge in now.

**Comment by rs1729** [comment]
Maybe my comment was not so clear
https://github.com/rs1729/RS/issues/48#issuecomment-1321264578
but that was about the latest mts01mod commit,
Temperature and horizontal velocity.
I didn't have information about the temperature sensor, though it looks like a thermistor. The approximation I chose didn't look too bad. I compared three soundings.
Could be that very high and very low temperatures show more deviation.
For relative humidity, my first impression was it needs calibration data. Or maybe the sensor/measurement was off at high altitude for one of the soundings, it showed a different offset than the other two. Plotting the raw data looked like there might be a simple linear mapping, but I didn't check yet. Maybe it depends on calibration data.

**Comment by rs1729** [comment]
@darksidelemm 
No, I didn't see the pull request here. There was no reaction to my comment/commit upstream.
@icalik 
Next time you take a file from upstream, you could mentioned it in the pull request or commit message, then it is clear that it is the same file, same changes.

**Pull request merged**
