### PR TITLE
Additional data displayed in the tooltip

### PR DESCRIPTION
**Pull request by Piter-NS**
Removed the double tooltip on the map and added additional data displayed in the tooltip, such as altitude, climb and horizontal speed.
A style has been added for the sondeTooltip class.

### CODE REVIEW

**Comment by darksidelemm** [comment]
Thanks!

**Comment by darksidelemm** [comment]
I just noticed the tooltip is always visible. This is probably fine, but I'll have a play with it during an actual flight and evaluate :-)

**Comment by LukePrior** [comment]
Is the tooltip also always visible on mobile because I can imagine that this it would get quite annoying, I think the previous functionality was ideal.

**Comment by LukePrior** [comment]
This also won't work for those who have imperial units enabled.

**Comment by darksidelemm** [comment]
Yeah all good points. It looks like it will behave the same on mobile as on desktop.
It actually doesn't look to bad on mobile. It's small enough that it doesn't cover too much. 

Screenshot_20210424-205620


Definitely needs to deal with both metric and imperial units though, and the altitude needs to be converted to fixed point in metres (currently its showing two un-necessary decimal points).

**Comment by LukePrior** [comment]
> It actually doesn't look to bad on mobile. It's small enough that it doesn't cover too much.

Will it disappear once the sonde is marked as old because if you have multiple it will get messy.

**Comment by darksidelemm** [comment]
Yeah, it won't. So yep, I think this needs to go back to being a hover-over thing.

**Pull request merged**
