### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by mjgardes**
Changing ftp server for [ephemeris file download for RS92](https://github.com/projecthorus/radiosonde_auto_rx/issues/364)

### CODE REVIEW

**Comment by darksidelemm** [comment]
Thanks for this! I've run it up manually and it grabs the data. I don't have any RS92s to test with, so if you say it works with sondes in the air, I'll trust you on that!

**Comment by darksidelemm** [comment]
@mjgardes It's looking like this change isn't always working. E.g. right now I just tried to run this and got the error:
```
DEBUG:root:GPS Grabber - Connecting to ESA's FTP Server...
DEBUG:root:GPS Grabber - Downloading ephemeris data file: brdc0750.21n.gz
ERROR:root:GPS Grabber - Could not download ephemeris file. - 550 File not found
```
Others are reporting similar issues. 

I suspect this may be because your solution is requesting a specific file - if ESA hasn't uploaded this file for whatever reason, then it breaks. My old solution would list the available files, and then pick the most recent one, so at least you would end up with a file that is still usable.

Is there a chance you can have a look into this?

**Comment by mjgardes** [comment]
Interesting.  ESA's brdc directory is a few days behind and the ephemeris information seems to go stale pretty quick so that might be about as useful as letting it fall back to almanac-only mode.

However, the daily folders are still current.  I'll try grabbing the latest from there.

**Comment by darksidelemm** [comment]
I've just pushed a change which uses the daily directory instead of the brdc directory. Hopefully this is reliable.

**Pull request merged**
