### PR TITLE
Relax Vaisala callsign regex, add option to log raw data to file.

### PR DESCRIPTION
**Pull request by darksidelemm**
WARNING: The raw data logging (new save_raw_data option) has only been tested on RS41 sondes. It still needs to be tested on all the other sondes auto_rx supports. Let me know if you encounter issues!

### CODE REVIEW

**Comment by F1TKE** [comment]
Hi, Imet prb with 1.5.4beta1 
Jun  3 23:23:42 RXRS auto_rx[12363]: 2021-06-03 23:23:42,807 INFO:Task Manager - SDR #0 has been allocated to Decoder (IMET, 402.997 MHz).
Jun  3 23:23:45 RXRS auto_rx[12363]: 2021-06-03 23:23:45,886 INFO:Decoder #0 IMET 402.997 - Starting decoder subprocess.
Jun  3 23:26:01 RXRS auto_rx[12363]: Exception in thread Thread-62:
Jun  3 23:26:01 RXRS auto_rx[12363]: Traceback (most recent call last):
Jun  3 23:26:01 RXRS auto_rx[12363]:   File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
Jun  3 23:26:01 RXRS auto_rx[12363]:     self.run()
Jun  3 23:26:01 RXRS auto_rx[12363]:   File "/usr/lib/python3.7/threading.py", line 865, in run
Jun  3 23:26:01 RXRS auto_rx[12363]:     self._target(*self._args, **self._kwargs)
Jun  3 23:26:01 RXRS auto_rx[12363]:   File "/home/pi/radiosonde_auto_rx/auto_rx/autorx/decode.py", line 1076, in decoder_thread
Jun  3 23:26:01 RXRS auto_rx[12363]:     _ok = self.handle_decoder_line(_line)
Jun  3 23:26:01 RXRS auto_rx[12363]:   File "/home/pi/radiosonde_auto_rx/auto_rx/autorx/decode.py", line 1286, in handle_decoder_line
Jun  3 23:26:01 RXRS auto_rx[12363]:     _telemetry["station_code"] = self.imet_location
Jun  3 23:26:01 RXRS auto_rx[12363]: AttributeError: 'SondeDecoder' object has no attribute 'imet_location'

**Comment by darksidelemm** [comment]
.. this is why we test :-)

Will fix shortly.

**Comment by F1TKE** [comment]
Yes ! with a lot of tester the final version run without prb.

**Comment by darksidelemm** [comment]
OK, should be fixed in the latest testing branch. Please test.

**Comment by F1TKE** [comment]
Test ok, Imet work again

**Pull request merged**
