### PR TITLE
Update send_file call to avoid deprecated argument

### PR DESCRIPTION
**Pull request by darksidelemm**

### CODE REVIEW

**Comment by argilo** [comment]
This change breaks log file downloads on "native" installs, because Raspberry Pi OS (Bullseye) ships with Flask 1.1.2. I guess the problem will be mostly resolved once Rasperry Pi OS updates to Bookworm (which ships with Flask 2.2.2).

**Comment by darksidelemm** [comment]
So if you remove the python3-flask package, then install flask via pip (e.g. pip3 install -r requirements.txt ) that should bring in the latest flask. 
I've removed python3-flask from the dependency install line in the install guide.

**Comment by argilo** [comment]
> I've removed python3-flask from the dependency install line in the install guide.

That seems like a good solution.

Installing flask through pip did solve the problem, as expected.

**Comment by darksidelemm** [comment]
Good to hear! Apologies about this, I haven't been focusing as much on the 'native' install instructions recently.

**Pull request merged**
