### PR TITLE
Add pre-commit

### PR DESCRIPTION
**Pull request by pinkavaj**
This allows improve source code base by unifying the look of the code and automatically removing fixing the issues.

### CODE REVIEW

**Comment by pinkavaj** [comment]
Btw there is an option to run this for each pull request or even push to a branch, if desired I can send related PR.

**Comment by darksidelemm** [comment]
I think i'd prefer to run the pre-commit changes myself once the other changes have been merged.

What do I need to do to do this?

**Comment by pinkavaj** [comment]
> I think i'd prefer to run the pre-commit changes myself once the other changes have been merged.
> 
> What do I need to do to do this?

* It is necessary to install the `pre-commit`, if you are on Linux it is likely part of your distribution.
* Goto source code directory and run `pre-commit install` - it installs the git hooks
* Run `pre-commit run -a` to run manually all the checks

If you get annoyed by it you can alwas remove the git hooks by running 'pre-commit uninstall` in the git repository folder.

**Comment by pinkavaj** [comment]
I have removed the fix of the linting issues from the MR. Feel free to do them on your own.

**Pull request merged**
