### PR TITLE
Allow use different types of receivers

### PR DESCRIPTION
**Pull request by pinkavaj**
Allow specify for each device type what kind of SDR it is, this allow combining networked and local SDRs from various sources or just use multiple network devices.

### CODE REVIEW

**Comment by pinkavaj** [comment]
@rs1729 Hi, just got this idea and investigating if it is right time to go this way. The code is not finished nor properly tested, the goal was just to show the idea. Best to see changes in sample config to get whats going on.

**Comment by darksidelemm** [comment]
I would prefer not to make this change. 

When in 'network SDR' mode, auto_rx assumes the network sdr supports multiple demodulators, and since we only support spyserver, that is definitely the case. The 'number of sdrs' option sets the number of demodulators to be used in parallel, which is mainly going to be limited by CPU.

When in RTLSDR mode, it does require one RTLSDR per demodulator.

I don't want to mix these two modes of operation.

**Comment by darksidelemm** [comment]
If you're on discord, it might be worth jumping on the #radiosonde_auto_Rx channel, where I, and a few other devs hang out to discuss: https://discord.gg/8sWUQKGY

**Comment by pinkavaj** [comment]
> If you're on discord, it might be worth jumping on the #radiosonde_auto_Rx channel, where I, and a few other devs hang out to discuss: https://discord.gg/8sWUQKGY

Unfortunately not now.

**Comment by pinkavaj** [comment]
@darksidelemm Hi, not sure what the discussion went, but from my point of view it is even a bit of waste to allow receive only 1 sonde on rtl-sdr, when there is the ~2.4MHz BW and in most cases the 8bit resolution is enough to receive many. But of course nontrivial amont of would would be needed to do this.

**Comment by darksidelemm** [comment]
Sure, I agree that the current way we use RTLSDRs is wasteful, however I do not want to have the DSP required to do this kind of thing (e.g. on-demand channelisation) within the auto_rx repository.

I have already described in detail what auto_rx needs in terms of spectrum and IQ data to operate here: https://github.com/projecthorus/radiosonde_auto_rx/issues/628

In the current testing branch, I have included the ability to connect to an SpyServer instance, which can do all of the above. With an Airspy Mini or Airspy R2, essentially the entire radiosonde band can be monitored simultaneously. 
RTLSDRs can also be used with SpyServer, but support for them appears to have been somewhat hobbled by the developer (who wants to sell Airspy units...).

The SDR wrapper code that is now in auto_rx should be fairly easily extended to support other spectrum/IQ sources when they become available. KA9Q's server is one that I hope to add support for, and hopefully some other options present themselves.

**Comment by pinkavaj** [comment]
Ok, lets close this. I will try to align with project goals and strategy. The KA9Q stuff looks interesting, i will do at least some exploration related to this problem here.

**Comment by darksidelemm** [comment]
I believe @rs1729 also has a server that he has been working on that might work too.

**Comment by rs1729** [comment]
Probably it would be easier to have it all integrated in one program and restrict to certain configurations, but that would be a different approach. In the modular approach of auto_rx you need some kind of server/clients communication.

There is
https://github.com/rs1729/RS/tree/master/demod/multi
that can decode certain types of radiosondes simultaneously. It has a basic way of adding and removing signals, but you would also need to scan the frequency band from time to time.

Don't know if it still possible, but you could use it manually via the UDP option in auto_rx.

https://github.com/rs1729/RS/tree/master/demod/iq_svcl
(https://github.com/projecthorus/radiosonde_auto_rx/issues/628#issuecomment-1073221184)
could provide IF IQ data for the decoders in a more general way, but I never tried to integrate it into auto_rx or other kind of automated monitoring and decoding.
And I don't know how it would perform on a RPi 4, probably not really good. But that's ok, these are only ideas of how it could work in principle, performance was not the primary goal.

**Comment by darksidelemm** [comment]
I think the IQ server/client approach is the right way about it, for auto_rx integration.

**Comment by rs1729** [comment]
However to perform on RPi4, it may be good to have a modified version that restricts to certain baseband and IF sample rates. This could be easier optimized (in particular the decimation).
Though I guess KA9Q's server will have good performance, maybe that will be the right alternative for auto_rx.

**Pull request closed without merging**
