### PR TITLE
Fix memset parametrization

### PR DESCRIPTION
**Pull request by pinkavaj**
The sizeof() and constant part were swapped.

### CODE REVIEW

**Comment by rs1729** [comment]
@pinkavaj 
Thanks for spotting this. Would you make a pull request at
https://github.com/rs1729/RS/tree/master/demod/mod
(m20mod.c aka mXXmod.c)
Them files more or less:
```
dfm09mod.c:1710:        memset(buffer_rawhex, BUFLEN+1, 0);
m10mod.c:1525:            memset(buffer_rawhex, 2*(FRAME_LEN+AUX_LEN)+12, 0);
//  meisei100mod.c:355:    dsp_t dsp = {0};  //memset(&dsp, 0, sizeof(dsp));
meisei100mod.c:705:                            memset(&gpx, sizeof(gpx), 0);
meisei100mod.c:870:                            memset(&gpx, sizeof(gpx), 0);
mXXmod.c:1363:            memset(buffer_rawhex, 2*(FRAME_LEN+AUX_LEN)+12, 0);
```

**Comment by pinkavaj** [comment]
> @pinkavaj Thanks for spotting this. Would you make a pull request at https://github.com/rs1729/RS/tree/master/demod/mod (m20mod.c aka mXXmod.c) Same files more or less:

Sure, I'm actually now going throught both repositories and just thinking if it would not be worth to sync them and eg. use the RS repository just as a git submodule here. It will deduplicate the code, both sides will get fresh updates and the attention would not be spread accross multiple repositories.

Is this somethink which can be considered as an option?

**Comment by rs1729** [comment]
Well, I suggested a submodule some time ago. I was thinking of making a new repository for that with only the stuff used in auto_rx, since in the RS-repo there are many things for historical reasons etc., it is more like a notebook I like to say.

**Comment by rs1729** [comment]
@darksidelemm 
fixed upstream.

**Comment by pinkavaj** [comment]
> Well, I suggested a submodule some time ago. I was thinking of making a new repository for that with only the stuff used in auto_rx, since in the RS-repo there are many things for historical reasons etc., it is more like a messy notebook I like to say.

I see the repository would need a bit of clean-up, but from what I see people are used to it. Sinc this is git, would it make sense to really just try to polish a bit the RS repository and re-consider the submodule stuff. I'm not yet too deep in this, but my experience is, forking is easy, but joining anythink back is the hard part ...

**Comment by rs1729** [comment]
I would like to have a cleaner/stripped `RS_autorx` repository for auto_rx that could be used as a submodule or in a subdirectory. Sometimes I'm not happy to make changes to the RS-repo even if it would make the code cleaner or more usable in auto_rx.
I would reconsider
https://github.com/projecthorus/radiosonde_auto_rx/issues/6
@darksidelemm ?

**Comment by darksidelemm** [comment]
Given we do occasionally make auto_rx specific changes to things, I'm still fine with just bringing in the updates as required, instead of going with a submodule.

**Comment by rs1729** [comment]
meisei100mod.c:

After fixing the memset() call, I realized that a complete reset of `gpx` that I had in mind would affect decoding (if a reset occurred).
`frame_(raw)bits` and Reed-Solomon `RS` must not be reset.

Fixed up stream.
```
-                        if (reset_gpx) {
-                            memset(&gpx, 0, sizeof(gpx));
+                        if (rst_gpx) {
+                            reset_gpx(&gpx);
```

Remark on `-Ofast/--fast-math`:
In `demod_mod.c` it speeds up floating point calculations, inaccuracies should be negligible, didn't observe unusual behavior.
However `meisei100mod.c` shouldn't be compiled with the fast-math flags because it is using the `isnan()` function, it would e.g. output `nan` values in JSON if temperature/humidity is nan.
I would (and do) use `-Ofast` only in `demod_mod.c` (and `dft_detect.c`, `imet4iq.c`, `mk2a1680mod.c`), `-O3` otherwise.

**Comment by darksidelemm** [comment]
I think we can close this one now, I've included the changes from upstream.

**Pull request closed without merging**
