### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by LukePrior**
This should be the changes you requested, please test.

### CODE REVIEW

**Comment by LukePrior** [comment]
I'm working on redesigning the entire interface not sure if I will finish it but here is what I've got. Any suggestions welcome!

image

image

**Comment by darksidelemm** [comment]
Hi Luke,

So I had been thinking about how i'd revise the auto_rx interface if I was going to do it. 
My intent was to bring it a bit more into line with the chasemapper interface. That is, a full-screen map, with data brought in with various tabs and controls that can be shown or hidden depending on what the user wants to see.
For example, the log could possibly be hidden by default, and opened up on demand. The SDR status (scanning, etc) would probably want to be displayed all the time somehow. The per-SDR information could end up being some kind of display that is added to the map (one per sonde) instead of a big table. This would make addition of data fields on a per-sonde basis a bit easier - e.g. dont even show the data if it isn't available (e.g. humidity, temperature, pressure). I would have pointed you at the wetterson.de interface as an example of that, but that seems to have been shut down.

As for making it work on both desktop and mobile devices... that's a big challenge to get right. Chasemapper barely works on devices with smaller than 7" screens, and I'm not sure I want to put in the extra effort to make it work well.

Cheers,
Mark

**Comment by LukePrior** [comment]
I settled on a design for the mobile version fairly happy with it.
Screenshot_2021-03-25-12-00-26-89
Screenshot_2021-03-25-12-00-22-27
Screenshot_2021-03-25-12-00-17-30

**Comment by LukePrior** [comment]
Is the time value passed through to the website in UTC?

**Comment by darksidelemm** [comment]
I think only time-of-day (HH:MM:SS, as a string) is passed through to the web interface, and yes, it will all be in UTC.

**Pull request merged**
